# Kích hoạt chế độ ngăn chặn trực tiếp của ModSecurity WAF
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off
SecResponseBodyMimeType text/plain text/html text/xml
SecDataDir /var/cache/modsecurity